DROP DATABASE IF EXISTS HeroTrackerTest;
CREATE DATABASE HeroTrackerTest;

USE HeroTrackerTest;

CREATE TABLE SuperPower(
	SuperPowerID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PowerName VARCHAR(100) NOT NULL,
    Description VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE Hero(
	HeroID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    HeroName VARCHAR(50) NOT NULL,
    SuperPowerID INT NOT NULL,
    Description VARCHAR(255) NULL,
    FOREIGN KEY (SuperPowerID) REFERENCES SuperPower(SuperPowerID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE Address(
	AddressID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Street1 VARCHAR(100) NOT NULL,
    Street2 VARCHAR(100) NULL,
    City VARCHAR(100) NOT NULL,
    State VARCHAR(25) NOT NULL,
    Zip VARCHAR(25) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE Location(
	LocationID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    AddressID INT NOT NULL, -- should this be req'd or ID by address OR GPS coordinates?
    LocationName VARCHAR(100) NULL,
    Description VARCHAR(255) NULL,
    LatitudeDegrees DECIMAL(5,2) NOT NULL,
    LatitudeDirection CHAR(1) NOT NULL,
    LongitudeDegrees DECIMAL(5,2) NOT NULL,
    LongitudeDirection CHAR(1) NOT NULL,
    FOREIGN KEY (AddressID) REFERENCES Address(AddressID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE Sighting(
	SightingID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    LocationID INT NOT NULL,
    SightingDate DATE NOT NULL,
    SightingTime DATETIME NULL,
    FOREIGN KEY (LocationID) REFERENCES Location(LocationID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE Organization(
	OrgID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    OrgName VARCHAR(50) NOT NULL,
    Description VARCHAR(255),
    HQAddressID INT NOT NULL,
    ContactName VARCHAR(50) NULL, -- Didn't feel like making a contact object
    ContactPhone VARCHAR(50) NULL,
    ContactEmail VARCHAR(50) NULL,
    FOREIGN KEY (HQAddressID) REFERENCES Address(AddressID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE OrganizationHero(
	OrgHeroID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	HeroID INT NOT NULL,
    OrgID INT NOT NULL,
    FOREIGN KEY (HeroID) REFERENCES Hero(HeroID),
    FOREIGN KEY (OrgID) REFERENCES Organization(OrgID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE HeroSighting(
	HeroSightingID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    HeroID INT NOT NULL,
    SightingID INT NOT NULL,
    FOREIGN KEY (HeroID) REFERENCES Hero(HeroID),
    FOREIGN KEY (SightingID) REFERENCES Sighting(SightingID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;